import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const studyPage = readFileSync(new URL('../js/study-page.js', import.meta.url), 'utf8');
const learningMode = readFileSync(new URL('../js/modes/learning-mode.js', import.meta.url), 'utf8');
const assessmentPage = readFileSync(new URL('../js/learning-assessment-page.js', import.meta.url), 'utf8');
const indexHtml = readFileSync(new URL('../index.html', import.meta.url), 'utf8');
const astrolabeAsset = readFileSync(new URL('../assets/academy-astrolabe-bg.webp', import.meta.url));
const taijiAsset = readFileSync(new URL('../assets/taiji-mechanism.webp', import.meta.url));

assert.match(studyPage, /export function renderLearningLessonPage/);
assert.match(studyPage, /一阴一阳之谓道/);
assert.match(studyPage, /《周易·系辞上传》/);
assert.match(studyPage, /class="lesson-stage-rail"/);
assert.match(studyPage, /class="lesson-method-rail"/);
assert.match(studyPage, /id="lesson-lead"/);
assert.match(studyPage, /id="lesson-observe"/);
assert.match(studyPage, /id="lesson-read"/);
assert.match(studyPage, /id="lesson-explain"/);
assert.match(studyPage, /id="lesson-apply"/);
assert.match(studyPage, /id="lesson-test"/);
assert.match(studyPage, /class="curriculum-track-map"/);
assert.match(studyPage, /lesson-overview-workspace/);
assert.match(studyPage, /class="study-path-overview"/);
assert.match(studyPage, /class="study-level-rail" aria-label="五阶学程"/);
assert.match(studyPage, /data-level-target=/);
assert.match(studyPage, /data-level-id=/);
assert.match(studyPage, /target\?\.scrollIntoView\(/);
assert.match(studyPage, /prefers-reduced-motion: reduce/);
assert.match(studyPage, /assets\/taiji-mechanism\.webp/);
assert.match(studyPage, /hexagramSvg\('111111'/);
assert.match(studyPage, /hexagramSvg\('000000'/);
assert.match(indexHtml, /易有太极，是生两仪；两仪生四象，四象生八卦。/);
assert.match(indexHtml, /class="workspace-insight-bar"/);
assert.equal(astrolabeAsset.subarray(0, 4).toString(), 'RIFF');
assert.equal(astrolabeAsset.subarray(8, 12).toString(), 'WEBP');
assert.equal(taijiAsset.subarray(0, 4).toString(), 'RIFF');
assert.equal(taijiAsset.subarray(8, 12).toString(), 'WEBP');
assert.match(learningMode, /renderLearningLessonPage\(content, appState, options\.lessonId/);
assert.match(learningMode, /\{ id: 'today', label: '今日修习' \}/);
assert.match(learningMode, /\{ id: 'path', label: '五阶学程' \}/);
assert.match(learningMode, /\{ id: 'library', label: '典籍书库' \}/);
assert.match(learningMode, /\{ id: 'profile', label: '修习谱' \}/);
assert.equal((learningMode.match(/\{ id: '[^']+', label: '[^']+' \}/g) || []).length, 4);
assert.match(learningMode, /class="today-practice"/);
assert.match(learningMode, /recommendLesson\(record\)/);
assert.match(learningMode, /class="library-grid"/);
assert.match(learningMode, /summarizeAchievements\(loadAchievementState\(\)\)/);
assert.match(learningMode, /yijing:workspace-insight/);
assert.match(learningMode, /panel\.scrollTop = 0/);
assert.match(learningMode, /heading\.focus\?\.\(\{ preventScroll: true \}\)/);
assert.match(assessmentPage, /function resetAssessmentViewport/);
assert.match(assessmentPage, /closest\?\.\('\.detail-panel'\)/);
assert.match(assessmentPage, /closest\?\.\('\.detail-content'\)/);
assert.match(assessmentPage, /id="assessment-sheet-title" data-page-heading/);
assert.match(assessmentPage, /id="assessment-result-title" data-page-heading/);
assert.match(assessmentPage, /<h3 data-page-heading>/);
assert.match(assessmentPage, /heading\.focus\?\.\(\{ preventScroll: true \}\)/);
assert.equal((assessmentPage.match(/resetAssessmentViewport\(/g) || []).length, 4);

console.log('✓ 学习首课、典籍依据与滚动复位契约通过');
